version: "3.4"
services:
  project-js:
    container_name: project-js
    image: node:18.12.1
    working_dir: /var/www/html/
    entrypoint: /bin/bash
    ports:
    - "3000:3000"
    volumes:
      - ./:/var/www/html
    tty: true